"""
Forex Bot - Phase 25: Portfolio Drawdown Distribution Audit
========================================================================
DIAGNOSTIC ONLY. No strategy modified, no parameter optimized, no new
strategy research. Uses ONLY existing historical trade-level data
already reconstructed in this project (data/phase20_trades.csv, the
exact frozen-parameter reconstruction from EXP-066..075). Builds the
combined 8-strategy portfolio trade stream, computes portfolio-level
drawdown/losing-streak statistics, runs a trade-order Monte Carlo, and
compares the current prop-account drawdown/losing-streak against that
historical distribution -- as a benchmark only, not a profitability claim.

DATA-QUALITY CORRECTION (documented, not silent): phase20's reconstruction
used risk_pct=0.005 (0.50%) for ALL THREE ARB strategies including
XAUUSD ARB. The frozen live weight for XAUUSD ARB is 0.25%, not 0.50%
(GBPJPY ARB and CADJPY ARB are correctly 0.50%). Since position size --
and therefore $ P&L -- scales linearly with risk_pct while R-multiples
do not, XAUUSD ARB's dollar P&L in phase20_trades.csv is corrected here
by x0.5 (0.25/0.50) before building the portfolio equity curve. R-multiples
are risk-normalized per trade and require no correction.

PORTFOLIO SIMULATION SIMPLIFICATION (documented): each strategy's dollar
P&L was originally generated by its own independent $100,000-balance
compounding simulation (phase20/`strategy_matrix_backtest.INITIAL_BALANCE`).
This script sums those 8 independently-compounding streams onto one
shared $100,000 reference starting capital to build a combined portfolio
equity curve -- the same simplification this project's own phase6/9
portfolio-model work already used. It does not model within-portfolio
compounding interaction between strategies (e.g. one strategy's drawdown
temporarily reducing the capital base available to another); this is a
known limitation, stated here rather than silently assumed away.

Requirements: none (uses only already-persisted data/phase20_trades.csv).
Output: reports/portfolio_drawdown_distribution_audit.md,
        reports/portfolio_drawdown_distribution_audit.csv
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent))

from strategy_matrix_backtest import REPO_ROOT

STARTING_CAPITAL = 100_000.0   # shared reference capital for the combined portfolio equity curve
N_MC_RUNS = 10_000
SEED = 71

# Frozen live risk weights (unchanged, not rescaled/optimized)
RISK_WEIGHTS = {
    'GBPJPY_ARB': 0.0050, 'CADJPY_ARB': 0.0050, 'XAUUSD_ARB': 0.0025,
    'GBPJPY_AMR': 0.0025, 'EURJPY_AMR': 0.0025, 'AUDJPY_AMR': 0.0025,
    'CADJPY_AMR': 0.0025, 'GBPUSD_MONDAY': 0.0025,
}
# risk_pct actually baked into phase20's dollar P&L reconstruction (for correction)
RECONSTRUCTED_RISK = {
    'GBPJPY_ARB': 0.0050, 'CADJPY_ARB': 0.0050, 'XAUUSD_ARB': 0.0050,
    'GBPJPY_AMR': 0.0025, 'EURJPY_AMR': 0.0025, 'AUDJPY_AMR': 0.0025,
    'CADJPY_AMR': 0.0025, 'GBPUSD_MONDAY': 0.0025,
}

JPY_STRATEGIES = ['GBPJPY_ARB', 'CADJPY_ARB', 'GBPJPY_AMR', 'EURJPY_AMR', 'AUDJPY_AMR', 'CADJPY_AMR']
NON_JPY_STRATEGIES = ['XAUUSD_ARB', 'GBPUSD_MONDAY']

LOG: list[str] = []


def say(msg=''):
    print(msg)
    LOG.append(str(msg))


# ═══════════════════════════════════════════════════════════════════════
# PART 1 -- PORTFOLIO RECONSTRUCTION
# ═══════════════════════════════════════════════════════════════════════

def load_and_correct() -> pd.DataFrame:
    df = pd.read_csv(REPO_ROOT / 'data' / 'phase20_trades.csv', parse_dates=['entry_time', 'exit_time'])
    df['pnl_corrected'] = df['pnl'] * (df['strategy'].map(RISK_WEIGHTS) / df['strategy'].map(RECONSTRUCTED_RISK))
    df = df.sort_values('entry_time').reset_index(drop=True)
    return df


def drawdown_episodes(equity: pd.Series) -> list[dict]:
    """Extract distinct peak-to-trough-to-recovery drawdown episodes from
    an equity curve. An episode starts when equity first drops below its
    running peak and ends when it returns to (or exceeds) that peak."""
    running_max = equity.cummax()
    in_dd = equity < running_max
    episodes = []
    i = 0
    n = len(equity)
    while i < n:
        if in_dd.iloc[i]:
            start = i
            peak = running_max.iloc[i]
            trough = equity.iloc[i]
            trough_idx = i
            while i < n and in_dd.iloc[i]:
                if equity.iloc[i] < trough:
                    trough = equity.iloc[i]
                    trough_idx = i
                i += 1
            episodes.append(dict(start_idx=start, trough_idx=trough_idx, end_idx=i - 1,
                                  peak=peak, trough=trough,
                                  depth_pct=100 * (peak - trough) / peak))
        else:
            i += 1
    return episodes


def main():
    say('=' * 90)
    say('PHASE 25 -- PORTFOLIO DRAWDOWN DISTRIBUTION AUDIT (diagnostic only, no strategy change)')
    say('=' * 90)
    say('PART 1 -- PORTFOLIO RECONSTRUCTION')
    say('Data source: data/phase20_trades.csv (EXP-066..075), frozen live parameters, unchanged.')
    say('CORRECTION: XAUUSD ARB dollar P&L rescaled x0.5 (reconstructed at 0.50% risk, frozen live')
    say('  weight is 0.25%) -- R-multiples require no correction (already risk-normalized per trade).')
    say(f'Combined portfolio equity curve built on a shared ${STARTING_CAPITAL:,.0f} reference capital,')
    say('  summing 8 independently-simulated strategies\' dollar P&L in chronological trade order --')
    say('  a known simplification (no cross-strategy compounding interaction modeled), stated here.')

    df = load_and_correct()
    say(f'\nRisk weights used (frozen, unchanged): {RISK_WEIGHTS}')
    say(f'Total trades loaded: {len(df)}, {df["entry_time"].min()} to {df["entry_time"].max()}')

    df['portfolio_equity'] = STARTING_CAPITAL + df['pnl_corrected'].cumsum()
    df['date'] = df['entry_time'].dt.date

    # ---- PART 2: portfolio-level metrics ----
    say('\n' + '=' * 90)
    say('PART 2 -- PORTFOLIO-LEVEL METRICS')
    say('=' * 90)

    n_trades = len(df)
    total_r = df['r_multiple'].sum()
    expectancy_r = df['r_multiple'].mean()
    expectancy_usd = df['pnl_corrected'].mean()
    wins = df[df.pnl_corrected > 0]['pnl_corrected'].sum()
    losses = -df[df.pnl_corrected < 0]['pnl_corrected'].sum()
    pf = wins / losses if losses > 0 else np.nan
    win_rate = (df.pnl_corrected > 0).mean()

    cum_r = df['r_multiple'].cumsum()
    max_dd_r = (cum_r - cum_r.cummax()).min()

    equity = df['portfolio_equity']
    running_max = equity.cummax()
    dd_pct_series = 100 * (equity - running_max) / running_max
    max_dd_pct = dd_pct_series.min()

    is_loss = (df['pnl_corrected'] < 0).to_numpy()
    max_streak, cur = 0, 0
    for x in is_loss:
        cur = cur + 1 if x else 0
        max_streak = max(max_streak, cur)

    daily_pnl = df.groupby('date')['pnl_corrected'].sum().sort_index()
    daily_loss = (daily_pnl < 0).to_numpy()
    max_losing_days, cur_d = 0, 0
    for x in daily_loss:
        cur_d = cur_d + 1 if x else 0
        max_losing_days = max(max_losing_days, cur_d)

    df['session_key'] = df['date'].astype(str) + '_' + df['session'].astype(str)
    session_pnl = df.groupby('session_key', sort=False)['pnl_corrected'].sum()
    session_pnl = session_pnl.reindex(df.drop_duplicates('session_key')['session_key'])  # chronological order
    session_loss = (session_pnl < 0).to_numpy()
    max_losing_sessions, cur_s = 0, 0
    for x in session_loss:
        cur_s = cur_s + 1 if x else 0
        max_losing_sessions = max(max_losing_sessions, cur_s)

    episodes = drawdown_episodes(equity)
    depths = [e['depth_pct'] for e in episodes if e['depth_pct'] > 0.01]  # ignore sub-0.01% noise
    avg_dd = np.mean(depths) if depths else np.nan
    median_dd = np.median(depths) if depths else np.nan
    n_gt = {th: sum(1 for d in depths if d >= th) for th in [1, 2, 3, 4, 5]}

    say(f'Total portfolio trades: {n_trades}')
    say(f'Total R: {total_r:+.2f}')
    say(f'Portfolio expectancy: {expectancy_r:+.4f}R  (${expectancy_usd:+,.2f} per trade on ${STARTING_CAPITAL:,.0f} reference capital)')
    say(f'Portfolio profit factor: {pf:.3f}')
    say(f'Portfolio win rate: {100*win_rate:.1f}%')
    say(f'Maximum drawdown in R: {max_dd_r:.2f}')
    say(f'Maximum drawdown as % of starting capital: {max_dd_pct:.2f}%')
    say(f'Maximum consecutive losing trades: {max_streak}')
    say(f'Maximum consecutive losing days: {max_losing_days}')
    say(f'Maximum consecutive losing trading sessions (date+session bucket): {max_losing_sessions}')
    say(f'Number of distinct drawdown episodes (>0.01%): {len(depths)}')
    say(f'Average drawdown depth: {avg_dd:.2f}%')
    say(f'Median drawdown depth: {median_dd:.2f}%')
    for th in [1, 2, 3, 4, 5]:
        say(f'  Drawdowns >= {th}%: {n_gt[th]}')

    part2 = dict(n_trades=n_trades, total_r=total_r, expectancy_r=expectancy_r,
                 expectancy_usd=expectancy_usd, pf=pf, win_rate=win_rate,
                 max_dd_r=max_dd_r, max_dd_pct=max_dd_pct, max_losing_streak=max_streak,
                 max_losing_days=max_losing_days, max_losing_sessions=max_losing_sessions,
                 n_drawdown_episodes=len(depths), avg_dd_pct=avg_dd, median_dd_pct=median_dd,
                 **{f'n_dd_gte_{th}pct': n_gt[th] for th in [1, 2, 3, 4, 5]})

    # ---- PART 3: Monte Carlo (trade-order shuffle, preserves the actual historical R/pnl set) ----
    say('\n' + '=' * 90)
    say(f'PART 3 -- MONTE CARLO ({N_MC_RUNS:,} trade-order-shuffle simulations)')
    say('=' * 90)
    say('Methodology: shuffle the ORDER of the actual historical trade set (same trades, same P&L')
    say('values, same eventual total -- order-invariant by construction), recompute the equity curve')
    say('and max drawdown / max losing streak for each shuffled order. This produces a distribution')
    say('of PATH-DEPENDENT outcomes (drawdown, streaks) consistent with the historical trade')
    say('population -- it does NOT prove future profitability, only characterizes the range of')
    say('drawdown/streak outcomes this specific set of historical trades could plausibly have produced')
    say('under a different arrival order.')

    rng = np.random.default_rng(SEED)
    pnl_arr = df['pnl_corrected'].to_numpy()
    loss_mask = pnl_arr < 0
    n = len(pnl_arr)

    mc_max_dd_pct = np.empty(N_MC_RUNS)
    mc_max_streak = np.empty(N_MC_RUNS, dtype=int)
    for run in range(N_MC_RUNS):
        perm = rng.permutation(n)
        shuffled = pnl_arr[perm]
        eq = STARTING_CAPITAL + np.cumsum(shuffled)
        run_max = np.maximum.accumulate(eq)
        dd = 100 * (eq - run_max) / run_max
        mc_max_dd_pct[run] = dd.min()

        losses_shuf = loss_mask[perm]
        streak = cur = 0
        for x in losses_shuf:
            cur = cur + 1 if x else 0
            streak = max(streak, cur)
        mc_max_streak[run] = streak

    dd_abs = -mc_max_dd_pct  # positive depth
    pctiles_dd = {p: np.percentile(dd_abs, p) for p in [50, 75, 90, 95, 99]}
    pctiles_streak = {p: np.percentile(mc_max_streak, p) for p in [50, 75, 90, 95, 99]}

    say(f'\nMax-drawdown distribution (% of starting capital, depth):')
    for p in [50, 75, 90, 95, 99]:
        say(f'  {p}th percentile: {pctiles_dd[p]:.2f}%')
    say(f'\nMax-losing-streak distribution:')
    for p in [50, 75, 90, 95, 99]:
        say(f'  {p}th percentile: {pctiles_streak[p]:.1f} trades')
    say(f'\nHistorical (actual chronological order) max drawdown: {-max_dd_pct:.2f}% '
        f'-- sits at the {100*np.mean(dd_abs <= -max_dd_pct):.1f}th percentile of the MC distribution')
    say(f'Historical (actual chronological order) max losing streak: {max_streak} trades '
        f'-- sits at the {100*np.mean(mc_max_streak <= max_streak):.1f}th percentile of the MC distribution')

    part3 = dict(**{f'mc_dd_p{p}pct': pctiles_dd[p] for p in [50, 75, 90, 95, 99]},
                 **{f'mc_streak_p{p}': pctiles_streak[p] for p in [50, 75, 90, 95, 99]})

    # ---- PART 4: current account comparison ----
    say('\n' + '=' * 90)
    say('PART 4 -- CURRENT PROP ACCOUNT COMPARISON')
    say('=' * 90)
    prop_dd_low, prop_dd_high = 3.4, 3.8
    prop_streak = 9
    for label, val in [('Prop DD (low estimate, -3.4%)', prop_dd_low), ('Prop DD (high estimate, -3.8%)', prop_dd_high)]:
        pctile = 100 * np.mean(dd_abs <= val)
        say(f'{label}: percentile of MC drawdown distribution = {pctile:.1f}th')
    streak_pctile = 100 * np.mean(mc_max_streak <= prop_streak)
    say(f'Prop losing streak (9 trades): percentile of MC losing-streak distribution = {streak_pctile:.1f}th')

    # ---- PART 6: JPY factor ----
    say('\n' + '=' * 90)
    say('PART 6 -- JPY FACTOR')
    say('=' * 90)
    df['is_jpy'] = df['strategy'].isin(JPY_STRATEGIES)
    pct_trades_jpy = 100 * df['is_jpy'].mean()
    df['risk_weight'] = df['strategy'].map(RISK_WEIGHTS)
    pct_risk_jpy = 100 * df.loc[df.is_jpy, 'risk_weight'].sum() / df['risk_weight'].sum()
    say(f'% of portfolio trades involving JPY strategies: {pct_trades_jpy:.1f}%')
    say(f'% of portfolio RISK-WEIGHT involving JPY strategies (sum of per-trade risk weights): {pct_risk_jpy:.1f}%')

    jpy_daily = df[df.is_jpy].pivot_table(index='date', columns='strategy', values='pnl_corrected', aggfunc='sum').fillna(0)
    corr = jpy_daily.corr()
    say('\nDaily P&L correlation matrix, JPY strategies:')
    say(corr.round(3).to_string())

    n_jpy_losing_by_day = (jpy_daily < 0).sum(axis=1)
    freq_2plus = 100 * (n_jpy_losing_by_day >= 2).mean()
    freq_3plus = 100 * (n_jpy_losing_by_day >= 3).mean()
    say(f'\nFrequency of 2+ JPY strategies losing same day: {freq_2plus:.2f}% of days with any JPY activity')
    say(f'Frequency of 3+ JPY strategies losing same day: {freq_3plus:.2f}% of days with any JPY activity')

    jpy_day_total = jpy_daily.sum(axis=1)
    worst_jpy_day = jpy_day_total.idxmin()
    say(f'Worst historical clustered JPY-loss day: {worst_jpy_day}, total ${jpy_day_total.min():+,.2f} '
        f'across {int(n_jpy_losing_by_day.loc[worst_jpy_day])} losing JPY strategies that day')
    say(jpy_daily.loc[worst_jpy_day].to_string())

    part6 = dict(pct_trades_jpy=pct_trades_jpy, pct_risk_jpy=pct_risk_jpy,
                 freq_2plus_jpy_loss_days_pct=freq_2plus, freq_3plus_jpy_loss_days_pct=freq_3plus,
                 worst_jpy_clustered_loss_usd=jpy_day_total.min())

    out_dir = REPO_ROOT / 'data'
    df.to_csv(out_dir / 'phase25_portfolio_trades.csv', index=False)
    pd.DataFrame(episodes).to_csv(out_dir / 'phase25_drawdown_episodes.csv', index=False)

    report_path = REPO_ROOT / 'reports' / 'phase25_audit_log.txt'
    report_path.write_text('\n'.join(LOG), encoding='utf-8')
    say(f'\nFull log written to {report_path}')

    return dict(**part2, **part3, **part6, prop_dd_low_pctile=100 * np.mean(dd_abs <= prop_dd_low),
                prop_dd_high_pctile=100 * np.mean(dd_abs <= prop_dd_high), prop_streak_pctile=streak_pctile)


if __name__ == '__main__':
    results = main()
    import json
    (REPO_ROOT / 'data' / 'phase25_summary.json').write_text(json.dumps(results, indent=2, default=str))
