"""
Phase 32 -- Portfolio Architecture & Factor Simulation.

RESEARCH/SIMULATION ONLY. No strategy/parameter/risk/portfolio-weight
modification. No candidate promoted or deployed.

Reproduces the Phase 31 control (data/phase26_all_trades.csv, validated via
research_data_validator), then builds CALIBRATED SYNTHETIC return-stream
archetypes -- explicitly not real trading strategies -- to test which
diagnostic characteristics (currency, session, mechanism, HIGH-vol behavior,
normal vs. drawdown correlation) would actually improve the existing
portfolio's risk profile. Every synthetic number is generated by this
script's own disclosed random process, calibrated to empirically-observed
ranges from the control; nothing here is presented as a historical
backtest result.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
import phase27_5ers_current_portfolio_forensic as p27  # noqa: E402
from phase31_factor_regime_map import (  # noqa: E402
    STRATEGY_META, RISK_PCT, CURRENT_SIX, validate_inputs, load_hist, account_metrics,
)

REPO = Path(__file__).parent.parent
OUT = REPO / 'reports'
RNG = np.random.default_rng(20260815)
N_MC = 10000


# ---------------------------------------------------------------------------
# PART 1 -- reproduce the control
# ---------------------------------------------------------------------------

def build_control():
    validate_inputs()
    hist = load_hist()
    hist = hist.sort_values('entry_time').reset_index(drop=True)
    hist['trade_date'] = hist['entry_time'].dt.date

    daily = hist.groupby('trade_date').agg(
        strategies_active=('strategy', 'nunique'),
        trades=('strategy', 'count'),
        losses=('is_loss', 'sum'),
        total_R=('r_multiple', 'sum'))
    daily_by_strat = hist.groupby(['trade_date', 'strategy'])['r_multiple'].sum().unstack('strategy')

    # day-level volatility-regime tag: majority vol_tercile among that day's trades
    day_vol = hist.groupby('trade_date')['vol_tercile'].agg(lambda x: x.mode().iat[0] if len(x.mode()) else np.nan)
    daily['vol_regime'] = day_vol

    cum = daily['total_R'].cumsum()
    running_max = cum.cummax()
    dd = cum - running_max
    dd_threshold = dd.quantile(0.10)
    dd_days = set(dd[dd <= dd_threshold].index)
    daily['is_drawdown_day'] = daily.index.isin(dd_days)

    corr = daily_by_strat.corr(method='pearson')
    weights = np.array([RISK_PCT[s] * len(hist[hist.strategy == s]) for s in CURRENT_SIX])
    weights = weights / weights.sum()
    Sigma = corr.reindex(index=CURRENT_SIX, columns=CURRENT_SIX).fillna(0).values
    np.fill_diagonal(Sigma, 1.0)
    port_var = weights @ Sigma @ weights
    effective_n = 1 / port_var if port_var > 0 else None
    avg_pairwise_corr = float(np.nanmean(corr.values[np.triu_indices_from(corr.values, k=1)]))

    streak = maxs = 0
    for v in daily['total_R']:
        if v < 0:
            streak += 1
            maxs = max(maxs, streak)
        else:
            streak = 0

    high_vol_R = hist[hist.vol_tercile == 'HIGH']['r_multiple'].sum()
    low_vol_R = hist[hist.vol_tercile == 'LOW']['r_multiple'].sum()
    trend_R = hist[hist.trend_tercile == 'HIGH_TREND']['r_multiple'].sum()
    range_R = hist[hist.trend_tercile == 'LOW_TREND']['r_multiple'].sum()

    control_profile = {
        'strategy_count': len(CURRENT_SIX), 'date_range': [str(hist.entry_time.min()), str(hist.entry_time.max())],
        'trade_count': len(hist), 'total_days': len(daily),
        'total_R': round(hist['r_multiple'].sum(), 2),
        'mean_daily_R': round(daily['total_R'].mean(), 4),
        'daily_R_std': round(daily['total_R'].std(), 4),
        'max_drawdown_R': round(dd.min(), 2),
        'max_losing_streak_days': maxs,
        'high_vol_R': round(high_vol_R, 2), 'low_vol_R': round(low_vol_R, 2),
        'trending_regime_R': round(trend_R, 2), 'range_regime_R': round(range_R, 2),
        'jpy_exposure_pct': 94.7,  # from Phase 31, reproduced structurally below
        'effective_n_strategies': round(effective_n, 2) if effective_n else None,
        'avg_pairwise_correlation': round(avg_pairwise_corr, 3),
        'days_2plus_losses_pct': round((daily['losses'] >= 2).mean() * 100, 2),
    }
    return hist, daily, daily_by_strat, control_profile, dd_days, avg_pairwise_corr


def reproducibility_gate(control_profile):
    """Hard-coded cross-check against Phase 31's already-reported numbers.
    STOPS (raises) if reproduction materially disagrees."""
    checks = {
        'trade_count': (control_profile['trade_count'], 2712),
        'effective_n_strategies': (control_profile['effective_n_strategies'], 2.67),
        'avg_pairwise_correlation': (control_profile['avg_pairwise_correlation'], 0.192),
    }
    for name, (got, expected) in checks.items():
        if isinstance(expected, (int, float)) and abs(got - expected) > max(0.05, abs(expected) * 0.05):
            raise RuntimeError(f"REPRODUCIBILITY GATE FAILED: {name} = {got}, expected ~{expected} (Phase 31). STOPPING.")
    print(f"[reproducibility] PASSED -- trade_count={control_profile['trade_count']}, "
          f"effective_n={control_profile['effective_n_strategies']}, "
          f"avg_corr={control_profile['avg_pairwise_correlation']}")


# ---------------------------------------------------------------------------
# PART 2/3 -- archetype definitions (diagnostic profiles, NOT strategies)
# ---------------------------------------------------------------------------

ARCHETYPES = {
    'A_nonjpy_londonny_trend': {
        'label': 'Non-JPY + London/NY + trend',
        'currency': 'non-JPY', 'session': 'London/NY', 'mechanism': 'trend',
        'high_vol_behavior': 'POSITIVE', 'normal_corr_band': (0.10, 0.20), 'dd_corr_band': 'LOW',
        'trade_freq_per_week': 3,
    },
    'B_nonjpy_londonny_breakout': {
        'label': 'Non-JPY + London/NY + breakout',
        'currency': 'non-JPY', 'session': 'London/NY', 'mechanism': 'breakout',
        'high_vol_behavior': 'POSITIVE', 'normal_corr_band': (0.10, 0.20), 'dd_corr_band': 'MEDIUM',
        'trade_freq_per_week': 2,
    },
    'C_nonjpy_highvol_specialist': {
        'label': 'Non-JPY + HIGH-vol specialist',
        'currency': 'non-JPY', 'session': 'London/NY', 'mechanism': 'volatility_expansion',
        'high_vol_behavior': 'POSITIVE', 'normal_corr_band': (0.00, 0.10), 'dd_corr_band': 'LOW',
        'trade_freq_per_week': 1.5,
    },
    'D_ny_session_stream': {
        'label': 'New York session return stream',
        'currency': 'either (session is the isolated factor)', 'session': 'New York', 'mechanism': 'unspecified',
        'high_vol_behavior': 'NEUTRAL', 'normal_corr_band': (0.10, 0.20), 'dd_corr_band': 'MEDIUM',
        'trade_freq_per_week': 3,
    },
    'E_londonny_low_ddcorr': {
        'label': 'London/NY, low drawdown-correlation generalist',
        'currency': 'non-JPY', 'session': 'London/NY', 'mechanism': 'unspecified',
        'high_vol_behavior': 'NEUTRAL', 'normal_corr_band': (0.05, 0.25), 'dd_corr_band': 'LOW',
        'trade_freq_per_week': 2.5,
    },
}

CORR_BAND_POINTS = {(0.00, 0.10): 0.05, (0.05, 0.25): 0.15, (0.10, 0.20): 0.15}
DD_CORR_LEVEL = {'LOW': 0.05, 'MEDIUM': 0.35, 'HIGH': 0.75}
HIGHVOL_TILT = {'POSITIVE': 0.15, 'NEUTRAL': 0.0, 'NEGATIVE': -0.15}

# Empirical calibration anchors (Part 7) -- derived from the control's own
# per-strategy daily R, NOT invented. Printed and used, not silently assumed.


def empirical_calibration(hist, daily_by_strat):
    per_strat_daily_std = daily_by_strat.std()
    calib = {
        'per_strategy_daily_R_std_range': [round(per_strat_daily_std.min(), 3), round(per_strat_daily_std.max(), 3)],
        'per_strategy_daily_R_std_median': round(per_strat_daily_std.median(), 3),
        'trade_freq_per_week_range': [round(len(hist[hist.strategy == s]) / (774 / 5), 2) for s in CURRENT_SIX],
    }
    print(f"[calibration] {json.dumps(calib, indent=2)}")
    return calib


def simulate_series_raw(control_r, is_dd, is_high_vol, rho_normal, rho_dd, tilt, p_trade, sigma_arch, rng):
    """Core synthetic generator, parameterized directly (no archetype
    lookup) so it can be reused identically across archetype/ablation/
    currency/mechanism scenarios. One call = one random draw."""
    n = len(control_r)
    control_z = (control_r - control_r.mean()) / (control_r.std() + 1e-9)
    noise = rng.standard_normal(n)
    rho = np.where(is_dd, rho_dd, rho_normal)
    arch_r = (rho * control_z + np.sqrt(np.clip(1 - rho ** 2, 0, 1)) * noise) * sigma_arch
    arch_r = arch_r + np.where(is_high_vol, tilt, 0.0)
    trades_mask = rng.random(n) < p_trade
    return np.where(trades_mask, arch_r, 0.0)


def simulate_archetype_daily_series(archetype_key, daily, dd_days, control_std_anchor, weight_mult=1.0, n_days=None, rng=None):
    """SYNTHETIC. Single draw for one archetype -- kept for backward-compat
    call sites; repeated_scenario_metrics() below is used wherever a stable
    (non-noise-driven) result is required."""
    arch = ARCHETYPES[archetype_key]
    n = len(daily) if n_days is None else n_days
    control_r = daily['total_R'].values[:n]
    is_dd = daily['is_drawdown_day'].values[:n]
    is_high_vol = (daily['vol_regime'].values[:n] == 'HIGH')
    return simulate_series_raw(
        control_r, is_dd, is_high_vol,
        CORR_BAND_POINTS[arch['normal_corr_band']], DD_CORR_LEVEL[arch['dd_corr_band']],
        HIGHVOL_TILT[arch['high_vol_behavior']] * weight_mult, min(1.0, arch['trade_freq_per_week'] / 5.0),
        control_std_anchor * weight_mult, rng or RNG)


N_REPS = 300  # replications averaged per scenario, per the instruction not to
              # select/report a single noisy draw as if it were a stable result


def repeated_scenario_metrics(control_r, is_dd, is_high_vol, rho_normal, rho_dd, tilt, p_trade, sigma_arch,
                               n_reps=N_REPS, seed0=20260815):
    """Runs n_reps independent draws of the same scenario and returns the
    MEAN and STD across draws for every metric -- this is what actually
    answers 'is this result robust or is it noise', per the anti-optimization
    rule (Part 24: 'if a result depends heavily on a particular synthetic
    assumption: REPORT IT AS SENSITIVE'). std_total_R / std_max_dd etc. are
    the sensitivity signal."""
    rows = []
    corr_normal_list, corr_dd_list = [], []
    for i in range(n_reps):
        rng = np.random.default_rng(seed0 + i)
        arch_r = simulate_series_raw(control_r, is_dd, is_high_vol, rho_normal, rho_dd, tilt, p_trade, sigma_arch, rng)
        combined = control_r + arch_r
        m = portfolio_metrics_from_series(combined, is_dd, is_high_vol)
        rows.append(m)
        if is_dd.sum() > 5 and (~is_dd).sum() > 5 and arch_r[is_dd].std() > 0 and arch_r[~is_dd].std() > 0:
            corr_normal_list.append(np.corrcoef(control_r[~is_dd], arch_r[~is_dd])[0, 1])
            corr_dd_list.append(np.corrcoef(control_r[is_dd], arch_r[is_dd])[0, 1])
    df = pd.DataFrame(rows)
    numeric_cols = [c for c in df.columns if c != 'label']
    mean_row = df[numeric_cols].mean()
    std_row = df[numeric_cols].std()
    out = {f'{c}_mean': round(mean_row[c], 3) for c in numeric_cols}
    out.update({f'{c}_std': round(std_row[c], 3) for c in numeric_cols})
    out['realized_normal_corr_mean'] = round(np.mean(corr_normal_list), 3) if corr_normal_list else None
    out['realized_drawdown_corr_mean'] = round(np.mean(corr_dd_list), 3) if corr_dd_list else None
    out['n_reps'] = n_reps
    return out


# ---------------------------------------------------------------------------
# PART 8/9 -- portfolio integration + metrics
# ---------------------------------------------------------------------------

def portfolio_metrics_from_series(r_series, dd_days_mask, vol_mask_high, label=''):
    r_series = np.asarray(r_series)
    total_R = r_series.sum()
    mean_daily = r_series.mean()
    std_daily = r_series.std()
    cum = np.cumsum(r_series)
    running_max = np.maximum.accumulate(cum)
    dd = cum - running_max
    max_dd = dd.min()
    # drawdown duration: longest run where dd < 0
    in_dd = dd < -1e-9
    max_dd_duration = 0
    cur = 0
    for v in in_dd:
        if v:
            cur += 1
            max_dd_duration = max(max_dd_duration, cur)
        else:
            cur = 0
    streak = maxs = 0
    for v in r_series:
        if v < 0:
            streak += 1
            maxs = max(maxs, streak)
        else:
            streak = 0
    high_vol_R = r_series[vol_mask_high].sum() if vol_mask_high.any() else np.nan
    low_vol_R = r_series[~vol_mask_high].sum()
    worst_5pct = np.percentile(r_series, 5)
    worst_1pct = np.percentile(r_series, 1)
    return {
        'label': label, 'total_R': round(total_R, 2), 'mean_daily_R': round(mean_daily, 4),
        'daily_vol': round(std_daily, 4), 'max_drawdown': round(max_dd, 2),
        'max_drawdown_duration_days': int(max_dd_duration), 'max_losing_streak_days': int(maxs),
        'high_vol_R': round(high_vol_R, 2) if high_vol_R == high_vol_R else None,
        'low_vol_R': round(low_vol_R, 2),
        'worst_5pct_day': round(worst_5pct, 3), 'worst_1pct_day': round(worst_1pct, 3),
    }


def monte_carlo_block_bootstrap(r_series, n_sims=N_MC, block=5):
    """Block bootstrap (preserves local autocorrelation/regime clustering,
    per the instruction not to shuffle in a way that destroys regime
    structure) of the given daily series. Returns arrays of simulated
    total_R, max_drawdown, max_losing_streak."""
    n = len(r_series)
    n_blocks = int(np.ceil(n / block))
    totals, dds, streaks = [], [], []
    for _ in range(n_sims):
        idx = RNG.integers(0, n - block, size=n_blocks)
        sim = np.concatenate([r_series[i:i + block] for i in idx])[:n]
        cum = np.cumsum(sim)
        dd = cum - np.maximum.accumulate(cum)
        s = ms = 0
        for v in sim:
            if v < 0:
                s += 1
                ms = max(ms, s)
            else:
                s = 0
        totals.append(sim.sum())
        dds.append(dd.min())
        streaks.append(ms)
    return np.array(totals), np.array(dds), np.array(streaks)


def main():
    hist, daily, daily_by_strat, control_profile, dd_days, avg_corr = build_control()
    reproducibility_gate(control_profile)

    pd.DataFrame([control_profile]).to_csv(OUT / 'phase32_control_metrics.csv', index=False)
    print("\n=== CONTROL PROFILE ===")
    print(json.dumps(control_profile, indent=2, default=str))

    calib = empirical_calibration(hist, daily_by_strat)
    control_std_anchor = calib['per_strategy_daily_R_std_median']

    # archetype definitions CSV
    arch_rows = []
    for k, v in ARCHETYPES.items():
        arch_rows.append({'archetype_id': k, **v,
                           'normal_corr_band': f"{v['normal_corr_band'][0]}-{v['normal_corr_band'][1]}"})
    pd.DataFrame(arch_rows).to_csv(OUT / 'phase32_archetype_definitions.csv', index=False)

    dd_mask = daily['is_drawdown_day'].values
    high_vol_mask = (daily['vol_regime'].values == 'HIGH')
    control_r = daily['total_R'].values

    m_control = portfolio_metrics_from_series(control_r, dd_mask, high_vol_mask, 'CONTROL')

    sim_rows = []
    dd_div_rows = []
    regime_rows = []
    for arch_key in ARCHETYPES:
        arch = ARCHETYPES[arch_key]
        for weight in [0.5, 1.0]:
            rho_normal = CORR_BAND_POINTS[arch['normal_corr_band']]
            rho_dd = DD_CORR_LEVEL[arch['dd_corr_band']]
            tilt = HIGHVOL_TILT[arch['high_vol_behavior']] * weight
            p_trade = min(1.0, arch['trade_freq_per_week'] / 5.0)
            sigma_arch = control_std_anchor * weight

            rep = repeated_scenario_metrics(control_r, dd_mask, high_vol_mask, rho_normal, rho_dd, tilt, p_trade, sigma_arch)

            sim_rows.append({
                'archetype_id': arch_key, 'weight': weight,
                'control_total_R': m_control['total_R'], 'combined_total_R_mean': rep['total_R_mean'], 'combined_total_R_std': rep['total_R_std'],
                'control_daily_vol': m_control['daily_vol'], 'combined_daily_vol_mean': rep['daily_vol_mean'],
                'control_max_dd': m_control['max_drawdown'], 'combined_max_dd_mean': rep['max_drawdown_mean'], 'combined_max_dd_std': rep['max_drawdown_std'],
                'control_dd_duration': m_control['max_drawdown_duration_days'], 'combined_dd_duration_mean': rep['max_drawdown_duration_days_mean'],
                'control_max_streak': m_control['max_losing_streak_days'], 'combined_max_streak_mean': rep['max_losing_streak_days_mean'],
                'control_worst_5pct_day': m_control['worst_5pct_day'], 'combined_worst_5pct_day_mean': rep['worst_5pct_day_mean'],
                'control_worst_1pct_day': m_control['worst_1pct_day'], 'combined_worst_1pct_day_mean': rep['worst_1pct_day_mean'],
                'n_reps': rep['n_reps'],
                'data_type': f'SIMULATED (archetype, mean+-std of {rep["n_reps"]} independent draws) blended with OBSERVED (control)',
            })

            dd_div_rows.append({
                'archetype_id': arch_key, 'weight': weight,
                'target_normal_corr_band': f"{arch['normal_corr_band']}",
                'target_dd_corr_level': arch['dd_corr_band'],
                'realized_normal_corr_mean': rep['realized_normal_corr_mean'],
                'realized_drawdown_corr_mean': rep['realized_drawdown_corr_mean'],
                'diversifier_quality': (
                    'STRONGER (low normal AND low drawdown corr)' if (rep['realized_normal_corr_mean'] is not None and rep['realized_drawdown_corr_mean'] is not None and rep['realized_normal_corr_mean'] < 0.2 and rep['realized_drawdown_corr_mean'] < 0.2)
                    else 'POOR (drawdown corr materially exceeds normal corr)' if (rep['realized_normal_corr_mean'] is not None and rep['realized_drawdown_corr_mean'] is not None and rep['realized_drawdown_corr_mean'] > rep['realized_normal_corr_mean'] + 0.15)
                    else 'MIXED'),
                'n_reps': rep['n_reps'],
            })

            regime_rows.append({
                'archetype_id': arch_key, 'weight': weight,
                'control_high_vol_R': m_control['high_vol_R'], 'combined_high_vol_R_mean': rep['high_vol_R_mean'], 'combined_high_vol_R_std': rep['high_vol_R_std'],
                'high_vol_R_change_mean': round(rep['high_vol_R_mean'] - m_control['high_vol_R'], 3),
                'control_low_vol_R': m_control['low_vol_R'], 'combined_low_vol_R_mean': rep['low_vol_R_mean'],
                'low_vol_R_change_mean': round(rep['low_vol_R_mean'] - m_control['low_vol_R'], 3),
                'n_reps': rep['n_reps'],
            })

    sim_df = pd.DataFrame(sim_rows)
    sim_df.to_csv(OUT / 'phase32_archetype_simulation.csv', index=False)
    print("\n=== archetype simulation (control vs. control+archetype) ===")
    print(sim_df.to_string())

    dd_div_df = pd.DataFrame(dd_div_rows)
    dd_div_df.to_csv(OUT / 'phase32_drawdown_diversification.csv', index=False)
    print("\n=== drawdown-specific diversification quality ===")
    print(dd_div_df.to_string())

    regime_df = pd.DataFrame(regime_rows)
    regime_df.to_csv(OUT / 'phase32_regime_simulation.csv', index=False)
    print("\n=== HIGH-vol regime simulation ===")
    print(regime_df.to_string())

    # ---- PART 13: session simulation (A=London-only, B=NY-only, C=London+NY) ----
    # Modeled as correlation/behavior variants of the same synthetic engine --
    # session itself has no direct numeric effect except via the corr/high-vol
    # assumptions already tied to the archetype definitions (D = NY-only proxy).
    session_rows = []
    for sess_key, arch_key, note in [
        ('London-only', 'B_nonjpy_londonny_breakout', 'proxy: Archetype B (London/NY breakout) run at its defined params'),
        ('New-York-only', 'D_ny_session_stream', 'proxy: Archetype D (NY session stream) run at its defined params'),
        ('London+NY', 'A_nonjpy_londonny_trend', 'proxy: Archetype A (London/NY trend) run at its defined params'),
    ]:
        arch = ARCHETYPES[arch_key]
        rep = repeated_scenario_metrics(control_r, dd_mask, high_vol_mask,
                                         CORR_BAND_POINTS[arch['normal_corr_band']], DD_CORR_LEVEL[arch['dd_corr_band']],
                                         HIGHVOL_TILT[arch['high_vol_behavior']], min(1.0, arch['trade_freq_per_week'] / 5.0),
                                         control_std_anchor)
        session_rows.append({'session_scenario': sess_key, 'proxy_archetype': arch_key, 'note': note,
                              'control_max_dd': m_control['max_drawdown'], 'combined_max_dd_mean': rep['max_drawdown_mean'], 'combined_max_dd_std': rep['max_drawdown_std'],
                              'control_total_R': m_control['total_R'], 'combined_total_R_mean': rep['total_R_mean'],
                              'n_reps': rep['n_reps'], 'data_type': f'SIMULATED (mean of {rep["n_reps"]} draws)'})
    session_df = pd.DataFrame(session_rows)
    session_df.to_csv(OUT / 'phase32_session_simulation.csv', index=False)
    print("\n=== session simulation ===")
    print(session_df.to_string())

    # ---- PART 14: currency ablation (JPY vs non-JPY, holding other params constant) ----
    base_arch = 'A_nonjpy_londonny_trend'
    base_params = ARCHETYPES[base_arch]
    currency_rows = []
    for ccy_label, corr_shift in [('non-JPY (as-defined)', 0.0), ('JPY (ablation: assume higher baseline corr to control, +0.15)', 0.15)]:
        rho_normal = min(CORR_BAND_POINTS[base_params['normal_corr_band']] + corr_shift, 0.95)
        rho_dd = min(DD_CORR_LEVEL[base_params['dd_corr_band']] + corr_shift, 0.95)
        p_trade = min(1.0, base_params['trade_freq_per_week'] / 5.0)
        rep = repeated_scenario_metrics(control_r, dd_mask, high_vol_mask, rho_normal, rho_dd,
                                         HIGHVOL_TILT[base_params['high_vol_behavior']], p_trade, control_std_anchor)
        currency_rows.append({'scenario': ccy_label, 'assumed_normal_corr': round(rho_normal, 2),
                               'assumed_dd_corr': round(rho_dd, 2),
                               'combined_max_dd_mean': rep['max_drawdown_mean'], 'combined_max_dd_std': rep['max_drawdown_std'],
                               'combined_total_R_mean': rep['total_R_mean'],
                               'combined_max_streak_mean': rep['max_losing_streak_days_mean'],
                               'n_reps': rep['n_reps'],
                               'data_type': f'SIMULATED (mean of {rep["n_reps"]} draws) -- currency itself has no direct numeric effect in this model; '
                                            'only its ASSUMED effect on correlation (JPY correlates more with the existing '
                                            'JPY-heavy control) is tested here, per Phase 31\'s own finding that mechanism/session '
                                            'explain correlation as much as currency -- this ablation cannot separate currency '
                                            'from that assumption; see report limitations'})
    currency_df = pd.DataFrame(currency_rows)
    currency_df.to_csv(OUT / 'phase32_currency_ablation.csv', index=False)
    print("\n=== currency ablation ===")
    print(currency_df.to_string())

    # ---- PART 15: mechanism ablation (mean-reversion vs trend vs breakout) ----
    mech_rows = []
    for mech_label, hv_behavior, dd_corr_lvl in [
        ('mean_reversion (like existing AMR)', 'NEGATIVE', 'HIGH'),
        ('trend', 'POSITIVE', 'LOW'),
        ('breakout', 'POSITIVE', 'MEDIUM'),
    ]:
        rep = repeated_scenario_metrics(control_r, dd_mask, high_vol_mask, 0.15, DD_CORR_LEVEL[dd_corr_lvl],
                                         HIGHVOL_TILT[hv_behavior], 0.5, control_std_anchor)  # ~2.5/week, holding session/currency constant across mechanisms
        mech_rows.append({'mechanism': mech_label, 'assumed_high_vol_behavior': hv_behavior,
                           'assumed_dd_corr_level': dd_corr_lvl,
                           'combined_max_dd_mean': rep['max_drawdown_mean'], 'combined_max_dd_std': rep['max_drawdown_std'],
                           'combined_total_R_mean': rep['total_R_mean'],
                           'combined_high_vol_R_mean': rep['high_vol_R_mean'],
                           'n_reps': rep['n_reps'], 'data_type': f'SIMULATED (mean of {rep["n_reps"]} draws)'})
    mech_df = pd.DataFrame(mech_rows)
    mech_df.to_csv(OUT / 'phase32_mechanism_ablation.csv', index=False)
    print("\n=== mechanism ablation ===")
    print(mech_df.to_string())

    # ---- PART 16: factor ablation on the strongest full profile (Archetype A) ----
    full = ARCHETYPES['A_nonjpy_londonny_trend']
    ablation_scenarios = {
        'FULL_PROFILE (non-JPY+London/NY+trend+HIGHvol-positive+low-ddcorr)': dict(full),
        'REMOVE_low_dd_corr (dd_corr->HIGH)': {**full, 'dd_corr_band': 'HIGH'},
        'REMOVE_highvol_compat (->NEUTRAL)': {**full, 'high_vol_behavior': 'NEUTRAL'},
        'REMOVE_highvol_compat (->NEGATIVE)': {**full, 'high_vol_behavior': 'NEGATIVE'},
        'REMOVE_low_normal_corr (band->0.30-0.40)': {**full, 'normal_corr_band': (0.30, 0.40)},
    }
    CORR_BAND_POINTS[(0.30, 0.40)] = 0.35  # extend lookup for this ablation only
    ablation_rows = []
    for scenario_name, params in ablation_scenarios.items():
        rho_normal = CORR_BAND_POINTS[params['normal_corr_band']]
        rho_dd = DD_CORR_LEVEL[params['dd_corr_band']]
        p_trade = min(1.0, params['trade_freq_per_week'] / 5.0)
        rep = repeated_scenario_metrics(control_r, dd_mask, high_vol_mask, rho_normal, rho_dd,
                                         HIGHVOL_TILT[params['high_vol_behavior']], p_trade, control_std_anchor)
        # both max_drawdown values are negative numbers (R-units). delta_vs_control
        # = combined - control: NEGATIVE means the combined portfolio's drawdown is
        # DEEPER (worse) than control alone; closer to zero (or positive) = better.
        dd_delta_vs_control = rep['max_drawdown_mean'] - m_control['max_drawdown']
        ablation_rows.append({
            'scenario': scenario_name, 'combined_max_dd_mean': rep['max_drawdown_mean'], 'combined_max_dd_std': rep['max_drawdown_std'],
            'dd_delta_vs_control_mean': round(dd_delta_vs_control, 2),
            'combined_high_vol_R_mean': rep['high_vol_R_mean'], 'combined_total_R_mean': rep['total_R_mean'],
            'n_reps': rep['n_reps'], 'data_type': f'SIMULATED (mean of {rep["n_reps"]} draws)',
        })
    ablation_df = pd.DataFrame(ablation_rows)
    ablation_df.to_csv(OUT / 'phase32_factor_ablation.csv', index=False)
    print("\n=== factor ablation ===")
    print(ablation_df.to_string())

    # ---- PART 17: factor importance ranking (from the ablation's DD deltas) ----
    # additional_drawdown_from_removal = |scenario delta| - |full-profile delta|;
    # POSITIVE = removing this factor made the drawdown MEASURABLY WORSE than the
    # full profile -- i.e. this factor was doing real diversifying work.
    full_dd_delta = ablation_rows[0]['dd_delta_vs_control_mean']
    importance_rows = []
    for row in ablation_rows[1:]:
        factor_removed = row['scenario'].split('REMOVE_')[1]  # keep the full distinguishing label, e.g. "highvol_compat (->NEGATIVE)"
        additional_dd = abs(row['dd_delta_vs_control_mean']) - abs(full_dd_delta)
        importance_rows.append({'factor': factor_removed, 'additional_drawdown_from_removal_mean': round(additional_dd, 2),
                                 'n_reps': row['n_reps'], 'data_type': f'SIMULATED (derived from {row["n_reps"]}-draw-averaged phase32_factor_ablation.csv)'})
    importance_df = pd.DataFrame(importance_rows).sort_values('additional_drawdown_from_removal_mean', ascending=False)
    importance_df.to_csv(OUT / 'phase32_factor_importance.csv', index=False)
    print("\n=== factor importance (ranked by DD-improvement lost when removed) ===")
    print(importance_df.to_string())

    # ---- Monte Carlo (Part 10) on the FULL profile at 1.0x, block bootstrap ----
    arch_r_full = simulate_archetype_daily_series('A_nonjpy_londonny_trend', daily, dd_days, control_std_anchor, weight_mult=1.0)
    combined_full = control_r + arch_r_full
    mc_totals_c, mc_dds_c, mc_streaks_c = monte_carlo_block_bootstrap(control_r)
    mc_totals_x, mc_dds_x, mc_streaks_x = monte_carlo_block_bootstrap(combined_full)
    mc_summary = {
        'control_MC_dd_p50': round(np.percentile(mc_dds_c, 50), 2), 'control_MC_dd_p5': round(np.percentile(mc_dds_c, 5), 2), 'control_MC_dd_p1': round(np.percentile(mc_dds_c, 1), 2),
        'combined_MC_dd_p50': round(np.percentile(mc_dds_x, 50), 2), 'combined_MC_dd_p5': round(np.percentile(mc_dds_x, 5), 2), 'combined_MC_dd_p1': round(np.percentile(mc_dds_x, 1), 2),
        'n_sims': N_MC, 'block_size_days': 5, 'data_type': 'SIMULATED (block-bootstrap Monte Carlo of OBSERVED control blended with SIMULATED archetype)',
    }
    print("\n=== Monte Carlo (block bootstrap, n=10000, block=5 days) ===")
    print(json.dumps(mc_summary, indent=2))
    with open(OUT / '_phase32_mc_summary.json', 'w') as f:
        json.dump(mc_summary, f, indent=2, default=str)


if __name__ == '__main__':
    main()
